[package]
name = "aoc"
version = "0.1.0"
edition = "2024"

[dependencies]
aoc-core = { path = "../aoc-core" }
aoc1 = { path = "../aoc1" }
aoc2 = { path = "../aoc2" }
aoc3 = { path = "../aoc3" }
aoc4 = { path = "../aoc4" }
aoc5 = { path = "../aoc5" }
aoc6 = { path = "../aoc6" }
aoc7 = { path = "../aoc7" }
